# Linear Algebra Basics with NumPy

### Matrix Mulitplication by using Loops.

Combines two matrices into one. Each output element is the dot product 
of a row from A and a column from B. Used in ML everywhere — a neural 
network layer is literally a matrix multiply: output = weights @ input.
Shape rule: (m×n) @ (n×p) = (m×p). Inner dimensions must match.

In [3]:
import numpy as np

In [40]:
a = np.array([[2,3],[2,4]])
b = np.array([[1,2],[6,7]])

In [44]:
result = np.zeros([2,2],int)
for i in range(0,2):
    for j in range(0,2):
        for k in range(0,2):
            sum+=int(a[i][k])*int(b[k][j])
        result[i][j]=sum
        sum = 0
result

array([[20, 25],
       [26, 32]])

Verifying our result with built-in NumPy methods:

In [50]:
np.allclose(result, a @ b) #verifying result. A@B --> Multiplication of A and B

True

Hadamard Product:
Element-wise multiplication. Same shape in, same shape out.
Used in: attention masks, gating mechanisms in LSTMs, 
and anywhere you want to scale individual elements independently.

In [49]:
a * b

array([[ 2,  6],
       [12, 28]])

### Dot Product without using built-in method.

Multiply corresponding elements, then sum. Single number output.
Measures how aligned two vectors are. If dot product = 0, vectors 
are perpendicular (orthogonal). Used in: similarity measures, 
projections, and every linear layer in a neural network.

In [61]:
v1 = np.array([1,2])
v2 = np.array([2,3])

In [67]:
v3 = 0
for i in range(0,2):
        v3+=int(v1[i])*int(v2[i])
v3

8

Verifying with numpy method

In [68]:
v4 = np.dot(v1,v2)
int(v4)

8

### Norms without using built-in method

Measures the "size" or "length" of a vector or matrix.

L1 norm = sum of absolute values. Used in Lasso regularization.
L2 norm = straight-line length. Used in Ridge regularization, 
gradient clipping, and k-NN distance.
Frobenius norm = L2 norm for matrices. Used to measure 
difference between two matrices (e.g. reconstruction error in PCA).

In [97]:
def lnorm(v,p,mat=False):
    if(p<1):
        return None
    norm = 0
    if (not mat):
        for i in range(0,len(v)):
            norm+=pow(int(v[i]),p)
        return pow(norm,1/p)
    else:
        for i in range(len(v)):
            for j in range(len(v[i])):
                norm+=pow(float(v[i][j]),2)
        return pow(norm,1/2)

In [77]:
v = np.array([1,2,3])

L1 norm from our method vs numpy method

In [78]:
lnorm(v,1)

6.0

In [79]:
np.linalg.norm(v,ord=1)

np.float64(6.0)

L2 norm from our method vs numpy method

In [80]:
lnorm(v,2)

3.7416573867739413

In [81]:
np.linalg.norm(v)

np.float64(3.7416573867739413)

Frobenius norm from our method vs numpy method

In [99]:
A = np.array([[1,2,3],[4,5,6]])
lnorm(A,1,mat=True)

9.539392014169456

In [101]:
np.linalg.norm(A, 'fro')

np.float64(9.539392014169456)

### Transpose of a Matrix

Flips rows and columns. (m×n) becomes (n×p).
Used constantly in ML: the normal equation is (X.T @ X)^-1 @ X.T @ y.
Key identity: (AB).T = B.T @ A.T — this appears in backprop derivations.

In [112]:
A = np.array([[1,2,3,4],[4,5,6,7]])
A

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [114]:
A.shape

(2, 4)

In [111]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6],
       [4, 7]])

In [115]:
A.T.shape

(4, 2)

### Matrix Inverse

A^-1 such that A @ A^-1 = I (identity).
Only square matrices can be inverted, only if det ≠ 0.
In ML: used in the normal equation for linear regression.
In practice: never actually invert — use np.linalg.solve() instead 
(faster and numerically stable).

In [117]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [119]:
B = np.linalg.inv(A)
B

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [120]:
A.dot(B)

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

### Determinant

Single number that describes how much a matrix scales area/volume.
det = 0 means the matrix is singular (not invertible) — it squishes 
space into a lower dimension. det < 0 means it flips orientation.
Used in: checking if a matrix is invertible, eigenvalue calculations.

In [121]:
np.linalg.det(A)

np.float64(-2.0000000000000004)

### Trace

Sum of diagonal elements = sum of eigenvalues.
Used in: regularization theory, measuring matrix "energy", 
and some loss functions in probabilistic models.


In [122]:
np.trace(A)

np.int64(5)

### Solving Ax=b (linear system)

Finding x given A and b. np.linalg.solve() is preferred over 
inv(A) @ b because it's faster and avoids numerical errors.
This is how linear regression's closed-form solution works:
X.T @ X is your A, X.T @ y is your b, theta is your x.

In [125]:
A = np.array([[1,2],[3,4]])
b = np.array([0,2])

In [130]:
x = np.linalg.solve(A,b)
x

array([ 2., -1.])

In [131]:
print(np.allclose(A @ x,b))

True


### Eigenvalues and Eigenvectors

Special vectors that only get scaled (not rotated) by a matrix.
A @ v = λ @ v. λ is the eigenvalue (scaling factor), v is the eigenvector.
Used in: PCA (eigenvectors of covariance matrix = principal components),
understanding matrix behavior, stability analysis.

In [132]:
A = np.array([[3,1],[0,2]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues: ",eigenvalues)
print("Eigenvectors(columns): ",eigenvectors)

Eigenvalues:  [3. 2.]
Eigenvectors(columns):  [[ 1.         -0.70710678]
 [ 0.          0.70710678]]


A @  v = λ @ v 

In [135]:
for i in range(len(eigenvalues)):
    lhs = A @ eigenvectors[:, i]
    rhs = eigenvalues[i] * eigenvectors[:, i]
    print(f"λ={eigenvalues[i]:.1f} verified:", np.allclose(lhs, rhs))

λ=3.0 verified: True
λ=2.0 verified: True


### Singular Value Decomposition

Breaks any matrix into 3 matrices: U @ diag(S) @ Vt.
Works on non-square matrices (unlike eigendecomposition).
S = singular values (like eigenvalues but for non-square).
Used in: PCA (sklearn uses SVD internally), recommendation systems,
dimensionality reduction, computing pseudoinverse.

In [147]:
A = np.array([[1,2],[3,4],[5,6]])
U, S, Vt = np.linalg.svd(A,full_matrices=False)
print("U:",U.shape)
print("S:", S)
print("Vt:",Vt.shape)

A_reconstructed = U @ np.diag(S) @ Vt
print("Reconstruction correct:", np.allclose(A, A_reconstructed))

U: (3, 2)
S: [9.52551809 0.51430058]
Vt: (2, 2)
Reconstruction correct: True
